image: maven:3.9-eclipse-temurin-17

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository

stages:
  - build
  - test
  - sonar
  - package
  - docker_build
  - docker_push
  - deploy

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile
  artifacts:
    paths:
      - target/classes
    expire_in: 1 hour

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/TEST-*.xml
    paths:
      - target/surefire-reports
      - target/site

sonar:
  stage: sonar
  rules:
    - if: $SONAR_TOKEN
  script:
    - mvn $MAVEN_CLI_OPTS verify sonar:sonar -Dsonar.projectKey={{CI_PROJECT_PATH}} -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN

package:
  stage: package
  script:
    - mvn $MAVEN_CLI_OPTS package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week

docker_build:
  stage: docker_build
  image: docker:27.1.1
  services:
    - docker:27.1.1-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u "{{CI_REGISTRY_USER}}" -p "{{CI_REGISTRY_PASSWORD}}" "{{CI_REGISTRY}}"
    - docker build -t "{{CI_REGISTRY}}/{{CI_PROJECT_PATH}}:{{CI_COMMIT_SHORT_SHA}}" -t "{{CI_REGISTRY}}/{{CI_PROJECT_PATH}}:latest" .
  only:
    - main
    - master
    - develop

docker_push:
  stage: docker_push
  image: docker:27.1.1
  services:
    - docker:27.1.1-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u "{{CI_REGISTRY_USER}}" -p "{{CI_REGISTRY_PASSWORD}}" "{{CI_REGISTRY}}"
    - docker push "{{CI_REGISTRY}}/{{CI_PROJECT_PATH}}:{{CI_COMMIT_SHORT_SHA}}"
    - docker push "{{CI_REGISTRY}}/{{CI_PROJECT_PATH}}:latest"
  only:
    - main
    - master
    - develop

deploy_staging:
  stage: deploy
  script:
    - echo "Deploying Spring Boot app to staging..."
  environment:
    name: staging
  only:
    - develop

deploy_production:
  stage: deploy
  script:
    - echo "Deploying Spring Boot app to production..."
  environment:
    name: production
  when: manual
  only:
    - main
    - master

