image: node:20-alpine

variables:
  PNPM_HOME: "$CI_PROJECT_DIR/.pnpm-store"

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store
    - node_modules

stages:
  - install
  - build
  - test
  - sonar
  - docker_build
  - docker_push
  - deploy

before_script:
  - npm install -g pnpm@8
  - pnpm config set store-dir $PNPM_HOME

install:
  stage: install
  script:
    - pnpm install --frozen-lockfile
  artifacts:
    paths:
      - node_modules
      - .pnpm-store
    expire_in: 1 hour

build:
  stage: build
  script:
    - pnpm run build
  artifacts:
    paths:
      - dist/
      - packages/*/dist/
    expire_in: 1 hour

test:
  stage: test
  script:
    - pnpm run test -- --coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    paths:
      - coverage/

# Matrix build for monorepo workspaces
build_workspace:
  stage: build
  parallel:
    matrix:
      - WORKSPACE: [app, api, ui, shared]
  script:
    - pnpm --filter $WORKSPACE run build
  artifacts:
    paths:
      - packages/$WORKSPACE/dist/
    expire_in: 1 hour
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /monorepo/

sonar:
  stage: sonar
  image: sonarsource/sonar-scanner-cli:latest
  rules:
    - if: $SONAR_TOKEN
  script:
    - sonar-scanner -Dsonar.projectKey={{CI_PROJECT_PATH}} -Dsonar.sources=. -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN

docker_build:
  stage: docker_build
  image: docker:27.1.1
  services:
    - docker:27.1.1-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_BUILDKIT: "1"
  script:
    - docker login -u "{{CI_REGISTRY_USER}}" -p "{{CI_REGISTRY_PASSWORD}}" "{{CI_REGISTRY}}"
    - docker build -t "{{CI_REGISTRY}}/{{CI_PROJECT_PATH}}:{{CI_COMMIT_SHORT_SHA}}" -t "{{CI_REGISTRY}}/{{CI_PROJECT_PATH}}:latest" .
  only:
    - main
    - master
    - develop

docker_push:
  stage: docker_push
  image: docker:27.1.1
  services:
    - docker:27.1.1-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u "{{CI_REGISTRY_USER}}" -p "{{CI_REGISTRY_PASSWORD}}" "{{CI_REGISTRY}}"
    - docker push "{{CI_REGISTRY}}/{{CI_PROJECT_PATH}}:{{CI_COMMIT_SHORT_SHA}}"
    - docker push "{{CI_REGISTRY}}/{{CI_PROJECT_PATH}}:latest"
  only:
    - main
    - master
    - develop

deploy_staging:
  stage: deploy
  script:
    - echo "Deploying pnpm monorepo to staging..."
  environment:
    name: staging
  only:
    - develop

deploy_production:
  stage: deploy
  script:
    - echo "Deploying pnpm monorepo to production..."
  environment:
    name: production
  when: manual
  only:
    - main
    - master

