using System.Text;
using Ci_Cd.Models;

namespace Ci_Cd.Services
{
    public class TemplateService : ITemplateService
    {
        private string TemplatesRoot => Path.Combine(AppContext.BaseDirectory, "templates");

        public TemplateService(ITemplateEngine engine)
        {
            // engine parameter kept for interface compatibility but not used in advanced generation
        }

        public string GenerateGitLabCi(RepoAnalysisResult analysis)
        {
            // Generate smart GitLab CI with all advanced features
            return GenerateAdvancedGitLabCi(analysis);
        }

        private string GenerateAdvancedGitLabCi(RepoAnalysisResult analysis)
        {
            var sb = new StringBuilder();
            
            sb.AppendLine("# Generated by advanced CI/CD generator");
            sb.AppendLine($"# Project: {analysis.ProjectName}, Language: {analysis.Language}");
            sb.AppendLine();
            sb.AppendLine("variables:");
            sb.AppendLine($"  BUILD_IMAGE: {analysis.GetBestImage()}");
            sb.AppendLine($"  PROJECT_NAME: {analysis.ProjectName}");
            sb.AppendLine("  DOCKER_DRIVER: overlay2");
            sb.AppendLine("  DOCKER_TLS_CERTDIR: \"/certs\"");
            
            foreach (var cache in analysis.CachingStrategy)
            {
                sb.AppendLine($"  {cache.Key.ToUpper()}_CACHE: {cache.Value}");
            }
            sb.AppendLine();

            // Stages
            var stages = new List<string> { "build", "test", "security", "docker", "publish", "deploy-staging", "deploy-production" };
            if (analysis.Subprojects.Count > 0)
            {
                stages.Insert(0, "matrix-build");
                stages.Insert(1, "matrix-test");
            }
            
            sb.AppendLine("stages:");
            foreach (var stage in stages)
            {
                sb.AppendLine($"  - {stage}");
            }
            sb.AppendLine();

            // Cache configuration
            GenerateCacheConfig(sb, analysis);
            
            // Matrix builds for monorepo
            if (analysis.Subprojects.Count > 0)
            {
                GenerateMatrixJobs(sb, analysis);
            }

            // Main build job
            GenerateBuildJob(sb, analysis);
            
            // Test jobs
            GenerateTestJobs(sb, analysis);
            
            // Security/SonarQube
            GenerateSecurityJob(sb, analysis);
            
            // Docker build
            GenerateDockerJob(sb, analysis);
            
            // Publish/Upload artifacts
            GeneratePublishJobs(sb, analysis);
            
            // Deployment jobs
            GenerateDeploymentJobs(sb, analysis);

            return sb.ToString();
        }
        
        private string SelectGitLabTemplate(RepoAnalysisResult analysis)
        {
            var lang = analysis.Language.ToString().ToLowerInvariant();
            var framework = analysis.Framework?.ToLowerInvariant() ?? "";
            
            // Java/Kotlin templates
            if (lang == "java" || lang == "kotlin")
            {
                if (framework.Contains("spring"))
                {
                    var hasGradle = File.Exists(Path.Combine(TemplatesRoot, "gradle")) || 
                        analysis.Dependencies.Any(d => d.Name.Contains("gradle", StringComparison.OrdinalIgnoreCase));
                    if (hasGradle)
                        return "java-spring-gradle.yml";
                    return "java-spring-maven.yml";
                }
            }
            
            // Go templates
            if (lang == "go")
            {
                return "go-modules.yml";
            }
            
            // Node.js/TypeScript templates
            if (lang == "nodejs" || lang == "typescript" || lang == "javascript")
            {
                if (File.Exists(Path.Combine(TemplatesRoot, "pnpm-workspace.yaml")) ||
                    File.Exists(Path.Combine(TemplatesRoot, "pnpm-lock.yaml")))
                    return "nodejs-pnpm-monorepo.yml";
                return "nodejs-npm.yml";
            }
            
            // Python templates
            if (lang == "python")
            {
                if (framework.Contains("django"))
                    return "python-django-poetry.yml";
                if (framework.Contains("fastapi") || framework.Contains("flask"))
                    return "python-fastapi-pip.yml";
                if (File.Exists(Path.Combine(TemplatesRoot, "pyproject.toml")))
                    return "python-django-poetry.yml";
                return "python-fastapi-pip.yml";
            }
            
            return "base.yml";
        }
        
        private string GenerateFallbackGitLabCi(RepoAnalysisResult analysis)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"image: {analysis.GetBestImage()}");
            sb.AppendLine();
            sb.AppendLine("stages:");
            sb.AppendLine("  - build");
            sb.AppendLine("  - test");
            sb.AppendLine("  - docker_build");
            sb.AppendLine("  - docker_push");
            sb.AppendLine();
            sb.AppendLine("build_job:");
            sb.AppendLine("  stage: build");
            sb.AppendLine("  script:");
            foreach (var cmd in analysis.BuildCommands) sb.AppendLine($"    - {cmd}");
            sb.AppendLine();
            sb.AppendLine("test_job:");
            sb.AppendLine("  stage: test");
            sb.AppendLine("  script:");
            foreach (var cmd in analysis.TestCommands) sb.AppendLine($"    - {cmd}");
            return sb.ToString();
        }

        public string GenerateJenkinsfile(RepoAnalysisResult analysis)
        {
            return GenerateAdvancedJenkinsfile(analysis);
        }

        private string GenerateAdvancedJenkinsfile(RepoAnalysisResult analysis)
        {
            var sb = new StringBuilder();
            
            sb.AppendLine("pipeline {");
            sb.AppendLine($"    agent {{ docker {{ image '{analysis.GetBestImage()}' }} }}");
            sb.AppendLine();
            
            // Environment variables
            sb.AppendLine("    environment {");
            sb.AppendLine($"        PROJECT_NAME = '{analysis.ProjectName}'");
            sb.AppendLine($"        BUILD_IMAGE = '{analysis.GetBestImage()}'");
            sb.AppendLine("        DOCKER_REGISTRY = credentials('docker-registry')");
            sb.AppendLine("        NEXUS_CREDENTIALS = credentials('nexus-credentials')");
            sb.AppendLine("        SONAR_TOKEN = credentials('sonar-token')");
            sb.AppendLine("        NPM_TOKEN = credentials('npm-token')");
            sb.AppendLine("    }");
            sb.AppendLine();
            
            // Options
            sb.AppendLine("    options {");
            sb.AppendLine("        buildDiscarder(logRotator(numToKeepStr: '10'))");
            sb.AppendLine("        timeout(time: 1, unit: 'HOURS')");
            sb.AppendLine("        retry(2)");
            sb.AppendLine("    }");
            sb.AppendLine();
            
            // Triggers
            sb.AppendLine("    triggers {");
            sb.AppendLine("        pollSCM('H/5 * * * *')");
            sb.AppendLine("    }");
            sb.AppendLine();
            
            // Stages
            sb.AppendLine("    stages {");
            
            // Matrix builds for monorepo
            if (analysis.Subprojects.Count > 0)
            {
                GenerateJenkinsMatrixStages(sb, analysis);
            }
            
            GenerateJenkinsBuildStage(sb, analysis);
            GenerateJenkinsTestStage(sb, analysis);
            GenerateJenkinsSonarStage(sb, analysis);
            GenerateJenkinsDockerStage(sb, analysis);
            GenerateJenkinsPublishStage(sb, analysis);
            GenerateJenkinsDeployStages(sb, analysis);
            
            sb.AppendLine("    }");
            sb.AppendLine();
            
            // Post actions
            sb.AppendLine("    post {");
            sb.AppendLine("        always {");
            sb.AppendLine("            publishHTML([");
            sb.AppendLine("                allowMissing: false,");
            sb.AppendLine("                alwaysLinkToLastBuild: true,");
            sb.AppendLine("                keepAll: true,");
            sb.AppendLine("                reportDir: 'target/site/jacoco',");
            sb.AppendLine("                reportFiles: 'index.html',");
            sb.AppendLine("                reportName: 'Coverage Report'");
            sb.AppendLine("            ])");
            sb.AppendLine("        }");
            sb.AppendLine("        success {");
            sb.AppendLine("            echo 'Pipeline succeeded!'");
            sb.AppendLine("        }");
            sb.AppendLine("        failure {");
            sb.AppendLine("            echo 'Pipeline failed!'");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            
            return sb.ToString();
        }
        
        private string GenerateFallbackJenkinsfile(RepoAnalysisResult analysis)
        {
            var sb = new StringBuilder();
            sb.AppendLine("pipeline {");
            sb.AppendLine($"  agent {{ docker {{ image '{analysis.GetBestImage()}' }} }}");
            sb.AppendLine("  stages {");
            sb.AppendLine("    stage('Build') {");
            sb.AppendLine("      steps {");
            foreach (var cmd in analysis.BuildCommands) sb.AppendLine($"        sh '{cmd}'");
            sb.AppendLine("      }");
            sb.AppendLine("    }");
            sb.AppendLine("  }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private void GenerateCacheConfig(StringBuilder sb, RepoAnalysisResult analysis)
        {
            sb.AppendLine("cache:");
            sb.AppendLine("  key: \"${CI_COMMIT_REF_SLUG}\"");
            sb.AppendLine("  paths:");
            
            // Language-specific cache paths
            switch (analysis.Language)
            {
                case RepoAnalysisResult.ProjectLanguage.Java when analysis.BuildTools.Contains("Maven"):
                    sb.AppendLine("    - .m2/repository/");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Java when analysis.BuildTools.Contains("Gradle"):
                    sb.AppendLine("    - .gradle/caches/");
                    sb.AppendLine("    - .gradle/wrapper/");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Kotlin:
                    sb.AppendLine("    - .gradle/caches/");
                    sb.AppendLine("    - .gradle/wrapper/");
                    sb.AppendLine("    - ~/.konan/");
                    break;
                case RepoAnalysisResult.ProjectLanguage.NodeJs when analysis.BuildTools.Contains("npm"):
                    sb.AppendLine("    - node_modules/");
                    sb.AppendLine("    - ~/.npm/");
                    break;
                case RepoAnalysisResult.ProjectLanguage.NodeJs when analysis.BuildTools.Contains("yarn"):
                    sb.AppendLine("    - node_modules/");
                    sb.AppendLine("    - .yarn/cache/");
                    break;
                case RepoAnalysisResult.ProjectLanguage.NodeJs when analysis.BuildTools.Contains("pnpm"):
                    sb.AppendLine("    - node_modules/");
                    sb.AppendLine("    - ~/.pnpm-store/");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Python when analysis.BuildTools.Contains("Poetry"):
                    sb.AppendLine("    - ~/.cache/pypoetry/");
                    sb.AppendLine("    - .venv/");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Python:
                    sb.AppendLine("    - ~/.cache/pip/");
                    sb.AppendLine("    - .venv/");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Go:
                    sb.AppendLine("    - ~/.cache/go-build/");
                    sb.AppendLine("    - ~/go/pkg/mod/");
                    break;
                case RepoAnalysisResult.ProjectLanguage.DotNet:
                    sb.AppendLine("    - ~/.nuget/packages/");
                    sb.AppendLine("    - obj/");
                    break;
                default:
                    sb.AppendLine("    - .cache/");
                    break;
            }
            sb.AppendLine();
        }

        private void GenerateMatrixJobs(StringBuilder sb, RepoAnalysisResult analysis)
        {
            sb.AppendLine("matrix-build:");
            sb.AppendLine("  stage: matrix-build");
            sb.AppendLine($"  image: $BUILD_IMAGE");
            sb.AppendLine("  parallel:");
            sb.AppendLine("    matrix:");
            
            foreach (var subproject in analysis.Subprojects.Take(5)) // Limit to 5 for performance
            {
                var projectName = Path.GetFileName(subproject);
                sb.AppendLine($"      - SUBPROJECT: {projectName}");
                var subprojectPath = subproject.Replace('\\', '/');
                sb.AppendLine($"        SUBPROJECT_PATH: {subprojectPath}");
            }
            
            sb.AppendLine("  script:");
            sb.AppendLine("    - cd $SUBPROJECT_PATH");
            sb.AppendLine("    - echo \"Building subproject $SUBPROJECT\"");
            
            // Language-specific commands for subprojects
            switch (analysis.Language)
            {
                case RepoAnalysisResult.ProjectLanguage.Java when analysis.BuildTools.Contains("Maven"):
                    sb.AppendLine("    - mvn clean package -DskipTests");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Java:
                    sb.AppendLine("    - ./gradlew build -x test --no-daemon");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Kotlin:
                    sb.AppendLine("    - echo \"Building Kotlin project with Gradle...\"");
                    sb.AppendLine("    - chmod +x gradlew || true");
                    sb.AppendLine("    - ./gradlew build -x test --no-daemon");
                    break;
                case RepoAnalysisResult.ProjectLanguage.NodeJs:
                    var tool = analysis.BuildTools.FirstOrDefault() ?? "npm";
                    sb.AppendLine($"    - {tool} install");
                    sb.AppendLine($"    - {tool} run build || echo 'No build script'");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Python:
                    if (analysis.BuildTools.Contains("Poetry"))
                    {
                        sb.AppendLine("    - poetry install");
                        sb.AppendLine("    - poetry build");
                    }
                    else
                    {
                        sb.AppendLine("    - pip install -r requirements.txt");
                    }
                    break;
                case RepoAnalysisResult.ProjectLanguage.Go:
                    sb.AppendLine("    - go mod download");
                    sb.AppendLine("    - go build ./...");
                    break;
                case RepoAnalysisResult.ProjectLanguage.DotNet:
                    sb.AppendLine("    - dotnet restore");
                    sb.AppendLine("    - dotnet build --configuration Release");
                    break;
                default:
                    foreach (var cmd in analysis.BuildCommands)
                    {
                        sb.AppendLine($"    - {cmd}");
                    }
                    break;
            }
            sb.AppendLine("  artifacts:");
            sb.AppendLine("    paths:");
            sb.AppendLine("      - $SUBPROJECT_PATH/target/");
            sb.AppendLine("      - $SUBPROJECT_PATH/build/");
            sb.AppendLine("      - $SUBPROJECT_PATH/dist/");
            sb.AppendLine();

            sb.AppendLine("matrix-test:");
            sb.AppendLine("  stage: matrix-test");
            sb.AppendLine("  image: $BUILD_IMAGE");
            sb.AppendLine("  needs: [\"matrix-build\"]");
            sb.AppendLine("  parallel:");
            sb.AppendLine("    matrix:");
            
            foreach (var subproject in analysis.Subprojects.Take(5))
            {
                var projectName = Path.GetFileName(subproject);
                sb.AppendLine($"      - SUBPROJECT: {projectName}");
                var subprojectPath = subproject.Replace('\\', '/');
                sb.AppendLine($"        SUBPROJECT_PATH: {subprojectPath}");
            }
            
            sb.AppendLine("  script:");
            sb.AppendLine("    - cd $SUBPROJECT_PATH");
            sb.AppendLine("    - echo \"Testing subproject $SUBPROJECT\"");
            
            // Language-specific test commands for subprojects
            switch (analysis.Language)
            {
                case RepoAnalysisResult.ProjectLanguage.Java when analysis.BuildTools.Contains("Maven"):
                    sb.AppendLine("    - mvn test");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Java:
                    sb.AppendLine("    - ./gradlew test");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Kotlin:
                    sb.AppendLine("    - ./gradlew test");
                    break;
                case RepoAnalysisResult.ProjectLanguage.NodeJs:
                    var tool = analysis.BuildTools.FirstOrDefault() ?? "npm";
                    sb.AppendLine($"    - {tool} test");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Python:
                    if (analysis.BuildTools.Contains("Poetry"))
                        sb.AppendLine("    - poetry run pytest");
                    else
                        sb.AppendLine("    - pytest");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Go:
                    sb.AppendLine("    - go test ./...");
                    break;
                case RepoAnalysisResult.ProjectLanguage.DotNet:
                    sb.AppendLine("    - dotnet test");
                    break;
                default:
                    foreach (var cmd in analysis.TestCommands)
                    {
                        sb.AppendLine($"    - {cmd}");
                    }
                    break;
            }
            sb.AppendLine("  coverage: '/Coverage: \\\\d+\\\\.\\\\d+%/'");
            sb.AppendLine();
        }

        private void GenerateBuildJob(StringBuilder sb, RepoAnalysisResult analysis)
        {
            sb.AppendLine("build:");
            sb.AppendLine("  stage: build");
            sb.AppendLine($"  image: $BUILD_IMAGE");
            sb.AppendLine("  script:");
            
            // Language-specific build commands
            switch (analysis.Language)
            {
                case RepoAnalysisResult.ProjectLanguage.Java when analysis.BuildTools.Contains("Maven"):
                    sb.AppendLine("    - echo \"Building Java project with Maven...\"");
                    sb.AppendLine("    - mvn clean compile");
                    sb.AppendLine("    - mvn package -DskipTests");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Java when analysis.BuildTools.Contains("Gradle"):
                    sb.AppendLine("    - echo \"Building Java project with Gradle...\"");
                    sb.AppendLine("    - chmod +x gradlew || true");
                    sb.AppendLine("    - ./gradlew build -x test --no-daemon");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Kotlin:
                    sb.AppendLine("    - echo \"Building Kotlin project with Gradle...\"");
                    sb.AppendLine("    - chmod +x gradlew || true");
                    sb.AppendLine("    - ./gradlew build -x test --no-daemon");
                    break;
                case RepoAnalysisResult.ProjectLanguage.NodeJs:
                    var buildTool = analysis.BuildTools.FirstOrDefault() ?? "npm";
                    sb.AppendLine($"    - echo \"Building Node.js project with {buildTool}...\"");
                    if (buildTool == "pnpm")
                    {
                        sb.AppendLine("    - pnpm install --frozen-lockfile");
                        sb.AppendLine("    - pnpm run build || echo 'No build script found'");
                    }
                    else if (buildTool == "yarn")
                    {
                        sb.AppendLine("    - yarn install --frozen-lockfile");
                        sb.AppendLine("    - yarn build || echo 'No build script found'");
                    }
                    else
                    {
                        sb.AppendLine("    - npm ci");
                        sb.AppendLine("    - npm run build || echo 'No build script found'");
                    }
                    break;
                case RepoAnalysisResult.ProjectLanguage.Python:
                    if (analysis.BuildTools.Contains("Poetry"))
                    {
                        sb.AppendLine("    - echo \"Building Python project with Poetry...\"");
                        sb.AppendLine("    - poetry install");
                        sb.AppendLine("    - poetry build");
                    }
                    else
                    {
                        sb.AppendLine("    - echo \"Building Python project with pip...\"");
                        sb.AppendLine("    - pip install -r requirements.txt");
                        sb.AppendLine("    - python setup.py build || echo 'No setup.py found'");
                    }
                    break;
                case RepoAnalysisResult.ProjectLanguage.Go:
                    sb.AppendLine("    - echo \"Building Go project...\"");
                    sb.AppendLine("    - go mod download");
                    sb.AppendLine("    - go build -v ./...");
                    break;
                case RepoAnalysisResult.ProjectLanguage.DotNet:
                    sb.AppendLine("    - echo \"Building .NET project...\"");
                    sb.AppendLine("    - dotnet restore");
                    sb.AppendLine("    - dotnet build --configuration Release --no-restore");
                    break;
                default:
                    sb.AppendLine("    - echo \"Building project with custom commands...\"");
                    foreach (var cmd in analysis.BuildCommands)
                    {
                        sb.AppendLine($"    - {cmd}");
                    }
                    break;
            }
            
            sb.AppendLine("  artifacts:");
            sb.AppendLine("    expire_in: 1 hour");
            sb.AppendLine("    paths:");
            
            // Improved artifact paths
            switch (analysis.Language)
            {
                case RepoAnalysisResult.ProjectLanguage.Java when analysis.BuildTools.Contains("Maven"):
                    sb.AppendLine("      - target/*.jar");
                    sb.AppendLine("      - target/classes/");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Java:
                    sb.AppendLine("      - build/libs/*.jar");
                    sb.AppendLine("      - build/classes/");
                    sb.AppendLine("      - target/*.jar");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Kotlin:
                    sb.AppendLine("      - build/libs/*.jar");
                    sb.AppendLine("      - build/classes/");
                    sb.AppendLine("      - build/kotlin/");
                    break;
                case RepoAnalysisResult.ProjectLanguage.NodeJs:
                    sb.AppendLine("      - dist/");
                    sb.AppendLine("      - build/");
                    sb.AppendLine("      - node_modules/");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Python:
                    sb.AppendLine("      - dist/");
                    sb.AppendLine("      - build/");
                    sb.AppendLine("      - \"*.whl\"");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Go:
                    sb.AppendLine("      - bin/");
                    sb.AppendLine("      - \"*.exe\"");
                    break;
                case RepoAnalysisResult.ProjectLanguage.DotNet:
                    sb.AppendLine("      - bin/Release/");
                    sb.AppendLine("      - obj/");
                    break;
            }
            
            sb.AppendLine("  rules:");
            sb.AppendLine("    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH");
            sb.AppendLine("    - if: $CI_COMMIT_BRANCH == \"develop\"");  
            sb.AppendLine("    - if: $CI_MERGE_REQUEST_IID");
            sb.AppendLine("    - if: $CI_COMMIT_TAG");
            sb.AppendLine();
        }

        private void GenerateTestJobs(StringBuilder sb, RepoAnalysisResult analysis)
        {
            sb.AppendLine("test:");
            sb.AppendLine("  stage: test");
            sb.AppendLine($"  image: $BUILD_IMAGE");
            sb.AppendLine("  needs: [\"build\"]");
            sb.AppendLine("  script:");
            
            // Language-specific test commands
            switch (analysis.Language)
            {
                case RepoAnalysisResult.ProjectLanguage.Java when analysis.BuildTools.Contains("Maven"):
                    sb.AppendLine("    - echo \"Running Java tests with Maven...\"");
                    sb.AppendLine("    - mvn test");
                    sb.AppendLine("    - mvn jacoco:report");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Java:
                    sb.AppendLine("    - echo \"Running Java tests with Gradle...\"");
                    sb.AppendLine("    - ./gradlew test");
                    sb.AppendLine("    - ./gradlew jacocoTestReport");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Kotlin:
                    sb.AppendLine("    - echo \"Running Kotlin tests with Gradle...\"");
                    sb.AppendLine("    - ./gradlew test");
                    sb.AppendLine("    - ./gradlew jacocoTestReport");
                    break;
                case RepoAnalysisResult.ProjectLanguage.NodeJs:
                    var tool = analysis.BuildTools.FirstOrDefault() ?? "npm";
                    sb.AppendLine($"    - echo \"Running Node.js tests with {tool}...\"");
                    sb.AppendLine($"    - {tool} test");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Python:
                    if (analysis.BuildTools.Contains("Poetry"))
                    {
                        sb.AppendLine("    - echo \"Running Python tests with Poetry...\"");
                        sb.AppendLine("    - poetry run pytest");
                    }
                    else
                    {
                        sb.AppendLine("    - echo \"Running Python tests with pytest...\"");
                        sb.AppendLine("    - pytest");
                    }
                    break;
                case RepoAnalysisResult.ProjectLanguage.Go:
                    sb.AppendLine("    - echo \"Running Go tests...\"");
                    sb.AppendLine("    - go test -v ./...");
                    sb.AppendLine("    - go test -race -coverprofile=coverage.out ./...");
                    break;
                case RepoAnalysisResult.ProjectLanguage.DotNet:
                    sb.AppendLine("    - echo \"Running .NET tests...\"");
                    sb.AppendLine("    - dotnet test --no-build --configuration Release");
                    sb.AppendLine("    - dotnet test --collect:\"XPlat Code Coverage\"");
                    break;
                default:
                    sb.AppendLine("    - echo \"Running tests with custom commands...\"");
                    foreach (var cmd in analysis.TestCommands)
                    {
                        sb.AppendLine($"    - {cmd}");
                    }
                    break;
            }
            
            // Add coverage reporting based on detected tools
            if (analysis.CoverageTools.Count > 0)
            {
                sb.AppendLine("  coverage: '/Coverage: \\d+\\.\\d+%/'");
                sb.AppendLine("  artifacts:");
                sb.AppendLine("    reports:");
                
                if (analysis.CoverageTools.Contains("JaCoCo"))
                {
                    sb.AppendLine("      coverage_report:");
                    sb.AppendLine("        coverage_format: jacoco");
                    sb.AppendLine("        path: target/site/jacoco/jacoco.xml");
                }
                else if (analysis.CoverageTools.Contains("Jest Coverage"))
                {
                    sb.AppendLine("      coverage_report:");
                    sb.AppendLine("        coverage_format: cobertura");
                    sb.AppendLine("        path: coverage/cobertura-coverage.xml");
                }
                else if (analysis.CoverageTools.Contains("coverage.py"))
                {
                    sb.AppendLine("      coverage_report:");
                    sb.AppendLine("        coverage_format: cobertura");
                    sb.AppendLine("        path: coverage.xml");
                }
            }
            sb.AppendLine();
        }

        private void GenerateSecurityJob(StringBuilder sb, RepoAnalysisResult analysis)
        {
            sb.AppendLine("sonarqube:");
            sb.AppendLine("  stage: security");
            sb.AppendLine("  image: sonarsource/sonar-scanner-cli");
            sb.AppendLine("  needs: [\"test\"]");
            sb.AppendLine("  script:");
            sb.AppendLine("    - sonar-scanner");
            sb.AppendLine("      -Dsonar.projectKey=$CI_PROJECT_NAME");
            sb.AppendLine("      -Dsonar.sources=.");
            sb.AppendLine("      -Dsonar.host.url=$SONAR_HOST");
            sb.AppendLine("      -Dsonar.login=$SONAR_TOKEN");
            sb.AppendLine("  rules:");
            sb.AppendLine("    - if: $SONAR_TOKEN");
            sb.AppendLine();
        }

        private void GenerateDockerJob(StringBuilder sb, RepoAnalysisResult analysis)
        {
            sb.AppendLine("docker:");
            sb.AppendLine("  stage: docker");
            sb.AppendLine("  image: docker:24.0");
            sb.AppendLine("  services:");
            sb.AppendLine("    - docker:24.0-dind");
            sb.AppendLine("  needs: [\"build\"]");
            sb.AppendLine("  variables:");
            sb.AppendLine("    DOCKER_IMAGE: \"$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA\"");
            sb.AppendLine("    DOCKER_IMAGE_LATEST: \"$CI_REGISTRY_IMAGE:latest\"");
            sb.AppendLine("  before_script:");
            sb.AppendLine("    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY");
            sb.AppendLine("  script:");
            sb.AppendLine("    - docker build -t $DOCKER_IMAGE -t $DOCKER_IMAGE_LATEST .");
            sb.AppendLine("    - docker push $DOCKER_IMAGE");
            sb.AppendLine("    - docker push $DOCKER_IMAGE_LATEST");
            sb.AppendLine("  rules:");
            sb.AppendLine("    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH");
            sb.AppendLine("    - if: $CI_COMMIT_TAG");
            sb.AppendLine();
        }

        private void GeneratePublishJobs(StringBuilder sb, RepoAnalysisResult analysis)
        {
            // Nexus/Artifactory publish
            sb.AppendLine("publish-nexus:");
            sb.AppendLine("  stage: publish");
            sb.AppendLine($"  image: $BUILD_IMAGE");
            sb.AppendLine("  needs: [\"test\"]");
            sb.AppendLine("  retry:");
            sb.AppendLine("    max: 2");
            sb.AppendLine("    when:");
            sb.AppendLine("      - runner_system_failure");
            sb.AppendLine("      - stuck_or_timeout_failure");
            sb.AppendLine("  script:");
            
            switch (analysis.Language)
            {
                case RepoAnalysisResult.ProjectLanguage.Java when analysis.BuildTools.Contains("Maven"):
                    sb.AppendLine("    - echo \"Publishing Maven artifact to Nexus...\"");
                    sb.AppendLine("    - mvn deploy -DskipTests=true");
                    sb.AppendLine("      -DaltDeploymentRepository=nexus::default::$NEXUS_URL/repository/maven-releases/");
                    sb.AppendLine("    - echo \"Verifying artifact upload...\"");
                    sb.AppendLine("    - wget --quiet --spider $NEXUS_URL/repository/maven-releases/ || echo 'Verification failed'");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Java when analysis.BuildTools.Contains("Gradle"):
                    sb.AppendLine("    - echo \"Publishing Gradle artifact...\"");
                    sb.AppendLine("    - ./gradlew publish");
                    sb.AppendLine("    - echo \"Verifying build artifacts...\"");
                    sb.AppendLine("    - test -f build/libs/*.jar || exit 1");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Kotlin:
                    sb.AppendLine("    - echo \"Publishing Kotlin artifact with Gradle...\"");
                    sb.AppendLine("    - ./gradlew publish");
                    sb.AppendLine("    - echo \"Verifying Kotlin build artifacts...\"");
                    sb.AppendLine("    - test -f build/libs/*.jar || exit 1");
                    break;
                case RepoAnalysisResult.ProjectLanguage.NodeJs:
                    sb.AppendLine("    - echo \"Publishing NPM package...\"");
                    sb.AppendLine("    - echo \"//registry.npmjs.org/:_authToken=$NPM_TOKEN\" > ~/.npmrc");
                    sb.AppendLine("    - npm publish --access public");
                    sb.AppendLine("    - echo \"Verifying package publication...\"");
                    sb.AppendLine("    - sleep 10 && npm view $PROJECT_NAME || echo 'Package not found yet'");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Python when analysis.BuildTools.Contains("Poetry"):
                    sb.AppendLine("    - echo \"Publishing Python wheel with Poetry...\"");
                    sb.AppendLine("    - poetry config repositories.nexus $NEXUS_URL/repository/pypi-hosted/");
                    sb.AppendLine("    - poetry publish --repository nexus --username $NEXUS_USER --password $NEXUS_PASSWORD");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Python:
                    sb.AppendLine("    - echo \"Publishing Python package with twine...\"");
                    sb.AppendLine("    - pip install twine");
                    sb.AppendLine("    - python setup.py sdist bdist_wheel");
                    sb.AppendLine("    - twine upload --repository-url $NEXUS_URL/repository/pypi-hosted/ dist/* -u $NEXUS_USER -p $NEXUS_PASSWORD");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Go:
                    sb.AppendLine("    - echo \"Publishing Go binary to GitHub Releases...\"");
                    sb.AppendLine("    - go build -ldflags \"-s -w\" -o bin/$PROJECT_NAME");
                    sb.AppendLine("    - echo \"Binary ready for release\"");
                    break;
                case RepoAnalysisResult.ProjectLanguage.DotNet:
                    sb.AppendLine("    - echo \"Publishing .NET package...\"");
                    sb.AppendLine("    - dotnet pack --configuration Release --no-build");
                    sb.AppendLine("    - dotnet nuget push bin/Release/*.nupkg --source $NEXUS_URL --api-key $NEXUS_API_KEY || echo 'Push failed'");
                    break;
                default:
                    sb.AppendLine("    - echo \"No publish command configured for this language\"");
                    break;
            }
            
            sb.AppendLine("  rules:");
            sb.AppendLine("    - if: $CI_COMMIT_TAG");
            sb.AppendLine("    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $NEXUS_URL");
            sb.AppendLine();

            // Docker push with retry
            sb.AppendLine("docker-push:");
            sb.AppendLine("  stage: publish");
            sb.AppendLine("  image: docker:24.0");
            sb.AppendLine("  services:");
            sb.AppendLine("    - docker:24.0-dind");
            sb.AppendLine("  needs: [\"docker\"]");
            sb.AppendLine("  retry:");
            sb.AppendLine("    max: 3");
            sb.AppendLine("    when:");
            sb.AppendLine("      - runner_system_failure");
            sb.AppendLine("      - stuck_or_timeout_failure");
            sb.AppendLine("      - api_failure");
            sb.AppendLine("  script:");
            sb.AppendLine("    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY");
            sb.AppendLine("    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA");
            sb.AppendLine("    - docker push $CI_REGISTRY_IMAGE:latest");
            sb.AppendLine("    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA || exit 1");
            sb.AppendLine("  rules:");
            sb.AppendLine("    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH");
            sb.AppendLine("    - if: $CI_COMMIT_TAG");
            sb.AppendLine();
        }

        private void GenerateDeploymentJobs(StringBuilder sb, RepoAnalysisResult analysis)
        {
            // Staging deployment
            sb.AppendLine("deploy-staging:");
            sb.AppendLine("  stage: deploy-staging");
            sb.AppendLine("  image: alpine/helm:latest");
            sb.AppendLine("  needs: [\"docker\"]");
            sb.AppendLine("  environment:");
            sb.AppendLine("    name: staging");
            sb.AppendLine("    url: https://staging.example.com");
            sb.AppendLine("  script:");
            sb.AppendLine("    - echo \"Deploying to staging environment\"");
            sb.AppendLine("    - helm upgrade --install $CI_PROJECT_NAME ./helm");
            sb.AppendLine("      --set image.repository=$CI_REGISTRY_IMAGE");
            sb.AppendLine("      --set image.tag=$CI_COMMIT_SHORT_SHA");
            sb.AppendLine("      --namespace staging");
            
            // Add detected ports
            foreach (var port in analysis.DetectedPorts)
            {
                sb.AppendLine($"      --set service.port={port.Key}");
            }
            
            sb.AppendLine("  rules:");
            sb.AppendLine("    - if: $CI_COMMIT_BRANCH == \"develop\"");
            sb.AppendLine("    - if: $CI_COMMIT_BRANCH =~ /^feature\\/.*$/");
            sb.AppendLine("      when: manual");
            sb.AppendLine();

            // Production deployment
            sb.AppendLine("deploy-production:");
            sb.AppendLine("  stage: deploy-production");
            sb.AppendLine("  image: alpine/helm:latest");
            sb.AppendLine("  needs: [\"docker\"]");
            sb.AppendLine("  environment:");
            sb.AppendLine("    name: production");
            sb.AppendLine("    url: https://production.example.com");
            sb.AppendLine("  script:");
            sb.AppendLine("    - echo \"Deploying to production environment\"");
            sb.AppendLine("    - helm upgrade --install $CI_PROJECT_NAME ./helm");
            sb.AppendLine("      --set image.repository=$CI_REGISTRY_IMAGE");
            sb.AppendLine("      --set image.tag=$CI_COMMIT_SHORT_SHA");
            sb.AppendLine("      --namespace production");
            
            foreach (var port in analysis.DetectedPorts)
            {
                sb.AppendLine($"      --set service.port={port.Key}");
            }
            
            sb.AppendLine("  rules:");
            sb.AppendLine("    - if: $CI_COMMIT_TAG");
            sb.AppendLine("    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH");
            sb.AppendLine("      when: manual");
            sb.AppendLine();
        }

        private void GenerateBuildCommands(StringBuilder sb, RepoAnalysisResult analysis, string prefix)
        {
            foreach (var cmd in analysis.BuildCommands)
            {
                sb.AppendLine($"{prefix}{cmd}");
            }
        }

        private void GenerateTestCommands(StringBuilder sb, RepoAnalysisResult analysis, string prefix)
        {
            foreach (var cmd in analysis.TestCommands)
            {
                sb.AppendLine($"{prefix}{cmd}");
            }
            
            // Add coverage generation based on detected tools
            if (analysis.CoverageTools.Contains("JaCoCo"))
                sb.AppendLine($"{prefix}mvn jacoco:report");
            else if (analysis.CoverageTools.Contains("Jest Coverage"))
                sb.AppendLine($"{prefix}npm run test:coverage");
            else if (analysis.CoverageTools.Contains("coverage.py"))
                sb.AppendLine($"{prefix}coverage xml");
        }

        private void GenerateJenkinsMatrixStages(StringBuilder sb, RepoAnalysisResult analysis)
        {
            sb.AppendLine("        stage('Matrix Build') {");
            sb.AppendLine("            matrix {");
            sb.AppendLine("                axes {");
            sb.AppendLine("                    axis {");
            sb.AppendLine("                        name 'SUBPROJECT'");
            var projects = string.Join("', '", analysis.Subprojects.Take(5));
            sb.AppendLine($"                        values '{projects}'");
            sb.AppendLine("                    }");
            sb.AppendLine("                }");
            sb.AppendLine("                stages {");
            sb.AppendLine("                    stage('Build Subproject') {");
            sb.AppendLine("                        steps {");
            sb.AppendLine("                            script {");
            sb.AppendLine("                                dir(\"${SUBPROJECT}\") {");
            sb.AppendLine("                                    echo \"Building ${SUBPROJECT}\"");
            sb.AppendLine("                                }");
            sb.AppendLine("                            }");
            sb.AppendLine("                        }");
            sb.AppendLine("                    }");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
        }

        private void GenerateJenkinsBuildStage(StringBuilder sb, RepoAnalysisResult analysis)
        {
            sb.AppendLine("        stage('Build') {");
            sb.AppendLine("            steps {");
            sb.AppendLine("                echo 'Starting build process...'");
            
            switch (analysis.Language)
            {
                case RepoAnalysisResult.ProjectLanguage.Java when analysis.BuildTools.Contains("Maven"):
                    sb.AppendLine("                sh 'mvn clean compile'");
                    sb.AppendLine("                sh 'mvn package -DskipTests'");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Java when analysis.BuildTools.Contains("Gradle"):
                    sb.AppendLine("                sh 'chmod +x gradlew || true'");
                    sb.AppendLine("                sh './gradlew build -x test --no-daemon'");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Kotlin:
                    sb.AppendLine("                sh 'chmod +x gradlew || true'");
                    sb.AppendLine("                sh './gradlew build -x test --no-daemon'");
                    break;
                case RepoAnalysisResult.ProjectLanguage.NodeJs:
                    var buildTool = analysis.BuildTools.FirstOrDefault() ?? "npm";
                    if (buildTool == "pnpm")
                    {
                        sb.AppendLine("                sh 'pnpm install --frozen-lockfile'");
                        sb.AppendLine("                sh 'pnpm run build || echo \"No build script found\"'");
                    }
                    else if (buildTool == "yarn")
                    {
                        sb.AppendLine("                sh 'yarn install --frozen-lockfile'");
                        sb.AppendLine("                sh 'yarn build || echo \"No build script found\"'");
                    }
                    else
                    {
                        sb.AppendLine("                sh 'npm ci'");
                        sb.AppendLine("                sh 'npm run build || echo \"No build script found\"'");
                    }
                    break;
                case RepoAnalysisResult.ProjectLanguage.Python:
                    if (analysis.BuildTools.Contains("Poetry"))
                    {
                        sb.AppendLine("                sh 'poetry install'");
                        sb.AppendLine("                sh 'poetry build'");
                    }
                    else
                    {
                        sb.AppendLine("                sh 'pip install -r requirements.txt'");
                        sb.AppendLine("                sh 'python setup.py build || echo \"No setup.py found\"'");
                    }
                    break;
                case RepoAnalysisResult.ProjectLanguage.Go:
                    sb.AppendLine("                sh 'go mod download'");
                    sb.AppendLine("                sh 'go build -v ./...'");
                    break;
                case RepoAnalysisResult.ProjectLanguage.DotNet:
                    sb.AppendLine("                sh 'dotnet restore'");
                    sb.AppendLine("                sh 'dotnet build --configuration Release --no-restore'");
                    break;
                default:
                    foreach (var cmd in analysis.BuildCommands)
                    {
                        sb.AppendLine($"                sh '{cmd.Replace("'", "\\'")}'");
                    }
                    break;
            }
            
            sb.AppendLine("            }");
            sb.AppendLine("            post {");
            sb.AppendLine("                success {");
            sb.AppendLine("                    archiveArtifacts artifacts: '**/*', allowEmptyArchive: true");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
        }

        private void GenerateJenkinsTestStage(StringBuilder sb, RepoAnalysisResult analysis)
        {
            sb.AppendLine("        stage('Test') {");
            sb.AppendLine("            steps {");
            sb.AppendLine("                echo 'Running tests...'");
            
            switch (analysis.Language)
            {
                case RepoAnalysisResult.ProjectLanguage.Java when analysis.BuildTools.Contains("Maven"):
                    sb.AppendLine("                sh 'mvn test'");
                    sb.AppendLine("                sh 'mvn jacoco:report'");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Java when analysis.BuildTools.Contains("Gradle"):
                    sb.AppendLine("                sh './gradlew test'");
                    sb.AppendLine("                sh './gradlew jacocoTestReport'");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Kotlin:
                    sb.AppendLine("                sh './gradlew test'");
                    sb.AppendLine("                sh './gradlew jacocoTestReport'");
                    break;
                case RepoAnalysisResult.ProjectLanguage.NodeJs:
                    var buildTool = analysis.BuildTools.FirstOrDefault() ?? "npm";
                    sb.AppendLine($"                sh '{buildTool} test'");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Python:
                    if (analysis.BuildTools.Contains("Poetry"))
                    {
                        sb.AppendLine("                sh 'poetry run pytest'");
                    }
                    else
                    {
                        sb.AppendLine("                sh 'pytest'");
                    }
                    break;
                case RepoAnalysisResult.ProjectLanguage.Go:
                    sb.AppendLine("                sh 'go test -v ./...'");
                    break;
                case RepoAnalysisResult.ProjectLanguage.DotNet:
                    sb.AppendLine("                sh 'dotnet test --no-build --configuration Release'");
                    break;
                default:
                    foreach (var cmd in analysis.TestCommands)
                    {
                        sb.AppendLine($"                sh '{cmd.Replace("'", "\\'")}'");
                    }
                    break;
            }
            
            sb.AppendLine("            }");
            sb.AppendLine("            post {");
            sb.AppendLine("                always {");
            sb.AppendLine("                    junit testResults: '**/target/surefire-reports/*.xml', allowEmptyResults: true");
            sb.AppendLine("                    publishHTML([");
            sb.AppendLine("                        allowMissing: false,");
            sb.AppendLine("                        alwaysLinkToLastBuild: true,");
            sb.AppendLine("                        keepAll: true,");
            sb.AppendLine("                        reportDir: 'target/site/jacoco',");
            sb.AppendLine("                        reportFiles: 'index.html',");
            sb.AppendLine("                        reportName: 'Test Coverage Report'");
            sb.AppendLine("                    ])");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
        }

        private void GenerateJenkinsSonarStage(StringBuilder sb, RepoAnalysisResult analysis)
        {
            sb.AppendLine("        stage('SonarQube Analysis') {");
            sb.AppendLine("            when {");
            sb.AppendLine("                environment name: 'SONAR_TOKEN', value: ''");
            sb.AppendLine("            }");
            sb.AppendLine("            steps {");
            sb.AppendLine("                withSonarQubeEnv('SonarQube') {");
            sb.AppendLine("                    sh '''");
            sb.AppendLine("                        sonar-scanner \\");
            sb.AppendLine("                          -Dsonar.projectKey=${PROJECT_NAME} \\");
            sb.AppendLine("                          -Dsonar.sources=. \\");
            sb.AppendLine("                          -Dsonar.host.url=${SONAR_HOST_URL} \\");
            sb.AppendLine("                          -Dsonar.login=${SONAR_TOKEN}");
            sb.AppendLine("                    '''");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
        }

        private void GenerateJenkinsDockerStage(StringBuilder sb, RepoAnalysisResult analysis)
        {
            sb.AppendLine("        stage('Docker Build') {");
            sb.AppendLine("            steps {");
            sb.AppendLine("                script {");
            sb.AppendLine("                    def image = docker.build(\"${PROJECT_NAME}:${BUILD_NUMBER}\")");
            sb.AppendLine("                    docker.withRegistry('https://registry.hub.docker.com', 'docker-registry') {");
            sb.AppendLine("                        image.push()");
            sb.AppendLine("                        image.push('latest')");
            sb.AppendLine("                    }");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
        }

        private void GenerateJenkinsPublishStage(StringBuilder sb, RepoAnalysisResult analysis)
        {
            sb.AppendLine("        stage('Publish') {");
            sb.AppendLine("            when {");
            sb.AppendLine("                anyOf {");
            sb.AppendLine("                    branch 'main'");
            sb.AppendLine("                    buildingTag()");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("            steps {");
            sb.AppendLine("                echo 'Publishing artifacts...'");
            
            switch (analysis.Language)
            {
                case RepoAnalysisResult.ProjectLanguage.Java when analysis.BuildTools.Contains("Maven"):
                    sb.AppendLine("                sh 'mvn deploy -DskipTests=true'");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Java when analysis.BuildTools.Contains("Gradle"):
                    sb.AppendLine("                sh './gradlew publish'");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Kotlin:
                    sb.AppendLine("                sh './gradlew publish'");
                    break;
                case RepoAnalysisResult.ProjectLanguage.NodeJs:
                    sb.AppendLine("                withCredentials([string(credentialsId: 'npm-token', variable: 'NPM_TOKEN')]) {");
                    sb.AppendLine("                    sh 'echo \"//registry.npmjs.org/:_authToken=$NPM_TOKEN\" > ~/.npmrc'");
                    sb.AppendLine("                    sh 'npm publish --access public'");
                    sb.AppendLine("                }");
                    break;
                case RepoAnalysisResult.ProjectLanguage.Python:
                    sb.AppendLine("                withCredentials([usernamePassword(credentialsId: 'pypi-credentials', usernameVariable: 'TWINE_USERNAME', passwordVariable: 'TWINE_PASSWORD')]) {");
                    sb.AppendLine("                    sh 'pip install twine'");
                    sb.AppendLine("                    sh 'twine upload dist/*'");
                    sb.AppendLine("                }");
                    break;
                case RepoAnalysisResult.ProjectLanguage.DotNet:
                    sb.AppendLine("                sh 'dotnet pack --configuration Release'");
                    sb.AppendLine("                sh 'dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY'");
                    break;
            }
            
            sb.AppendLine("            }");
            sb.AppendLine("        }");
        }

        private void GenerateJenkinsDeployStages(StringBuilder sb, RepoAnalysisResult analysis)
        {
            // Staging deployment
            sb.AppendLine("        stage('Deploy to Staging') {");
            sb.AppendLine("            when {");
            sb.AppendLine("                branch 'develop'");
            sb.AppendLine("            }");
            sb.AppendLine("            steps {");
            sb.AppendLine("                echo 'Deploying to staging environment...'");
            sb.AppendLine("                sh 'echo \"Deployment commands would go here\"'");
            sb.AppendLine("            }");
            sb.AppendLine("        }");

            // Production deployment
            sb.AppendLine("        stage('Deploy to Production') {");
            sb.AppendLine("            when {");
            sb.AppendLine("                anyOf {");
            sb.AppendLine("                    branch 'main'");
            sb.AppendLine("                    buildingTag()");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("            input {");
            sb.AppendLine("                message 'Deploy to production?'");
            sb.AppendLine("                ok 'Deploy'");
            sb.AppendLine("            }");
            sb.AppendLine("            steps {");
            sb.AppendLine("                echo 'Deploying to production environment...'");
            sb.AppendLine("                sh 'echo \"Production deployment commands would go here\"'");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
        }
    }
}
